title: KafClaw Docs
description: KafClaw product, operations, and administration documentation.
url: https://kafclaw.scalytics.io
baseurl: ""
logo: /assets/kafclaw.png
author: KafClaw
twitter:
  card: summary_large_image
  username: kafclaw
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: /assets/kafclaw.png
  - scope:
      path: "index.md"
    values:
      layout: "home"
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "KafClaw on GitHub":
    - "https://github.com/KafClaw/KafClaw"
footer_content: >-
  <span style="font-size:0.78rem;line-height:1.35;">
  Apache®, Apache Wayang®, Wayang®, Apache Kafka®, Kafka®, Apache Flink®, Flink®, Apache Iceberg®, Iceberg®, Apache Spark®, Spark® and associated open source project names are trademarks of the Apache Software Foundation.
  <br>
  Maintained and developed by Scalytics (<a href="https://www.scalytics.io">www.scalytics.io</a>).
  </span>
