title: KafClaw Docs
description: KafClaw product, operations, and administration documentation.
theme: just-the-docs
plugins:
  - jekyll-include-cache
markdown: kramdown
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "index.md"
    values:
      layout: "home"
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "KafClaw on GitHub":
    - "https://github.com/KafClaw/KafClaw"
footer_content: >-
  <span style="font-size:0.78rem;line-height:1.35;">
  Apache®, Apache Wayang®, Wayang®, Apache Kafka®, Kafka®, Apache Flink®, Flink®, Apache Iceberg®, Iceberg®, Apache Spark®, Spark® and associated open source project names are trademarks of the Apache Software Foundation.
  <br>
  Maintained and developed by Scalytics (<a href="https://www.scalytics.io">www.scalytics.io</a>).
  </span>
